kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: nas1-nfs-csi
spec:
  storageClassName: nas1-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-iscsi
  annotations:
    volume.beta.kubernetes.io/storage-class: nas1-iscsi-csi
spec:
  storageClassName: nas1-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command:
            - sleep
            - "infinity"
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /app/folder
              name: volume
            - mountPath: /app/folder2
              name: volume-iscsi
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: test-claim-nfs
        - name: volume-iscsi
          persistentVolumeClaim:
            claimName: test-claim-iscsi
