apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  labels:
    kubernetes.io/metadata.name: democratic-csi
    name: democratic-csi
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
