apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
    kubernetes.io/metadata.name: metallb-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 10.250.11.180-10.250.11.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-pool-1
  namespace: metallb-system
spec:
  ipAddressPools:
    - l2-pool-1
